Repository bonsai-rx/bonsai, pull requests merged in 2023-07, with the labels that each got.

#1444 Refactor default serial port implementation to avoid event callbacks
  Bonsai.System/IO/Ports/ObservableSerialPort.cs
  Bonsai.System/IO/Ports/PollingSerialPort.cs
  Bonsai.System/IO/Ports/SerialPortManager.cs
Labels: feature, proposal

#1445 Refactor arduino interface to avoid event callback
  .git-blame-ignore-revs
  Bonsai.Arduino/AnalogInput.cs
  Bonsai.Arduino/AnalogInputReceivedEventArgs.cs
  Bonsai.Arduino/AnalogOutput.cs
  Bonsai.Arduino/Arduino.cs
  Bonsai.Arduino/ArduinoConfiguration.cs
  Bonsai.Arduino/ArduinoConfigurationCollection.cs
  Bonsai.Arduino/ArduinoDisposable.cs
  Bonsai.Arduino/ArduinoManager.cs
  Bonsai.Arduino/Bonsai.Arduino.csproj
  Bonsai.Arduino/CreateArduino.cs
  Bonsai.Arduino/DigitalInput.cs
  Bonsai.Arduino/DigitalInputReceivedEventArgs.cs
  Bonsai.Arduino/DigitalOutput.cs
  Bonsai.Arduino/InputPullUp.cs
  Bonsai.Arduino/ObservableArduino.cs
  Bonsai.Arduino/PortNameConverter.cs
  Bonsai.Arduino/Properties/AssemblyInfo.cs
  Bonsai.Arduino/Properties/launchSettings.json
  Bonsai.Arduino/ReceiveSysex.cs
  Bonsai.Arduino/SendSysex.cs
  Bonsai.Arduino/ServoOutput.cs
  Bonsai.Arduino/SysexReceivedEventArgs.cs
  Bonsai.StarterPack/Bonsai.StarterPack.csproj
  Bonsai.sln
Labels: feature

#1446 Refactor text visualizer to use buffered updates
  Bonsai.Design/BufferedVisualizer.cs
  Bonsai.Design/ObjectTextVisualizer.cs
Labels: feature

#1449 Add source item template for dotnet new
  Bonsai.Audio/Bonsai.Audio.csproj
  Bonsai.Scripting/Bonsai.Scripting.csproj
  Bonsai.System.Design/Bonsai.System.Design.csproj
  Bonsai.System.Tests/Bonsai.System.Tests.csproj
  Bonsai.Templates/Bonsai.SourceTemplate/.template.config/template.json
  Bonsai.Templates/Bonsai.Templates.csproj
  Bonsai.Vision.Design/Bonsai.Vision.Design.csproj
Labels: feature

#1450 Add community code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#1451 Remove XML serialization properties from public API
  Bonsai.Core/Expressions/ExternalizedDateTimeOffset.cs
  Bonsai.Core/Expressions/ExternalizedTimeSpan.cs
  Bonsai.Core/Expressions/Properties/DateTimeOffsetProperty.cs
  Bonsai.Core/Expressions/Properties/TimeSpanProperty.cs
  Bonsai.Core/Expressions/ReplaySubjectBuilder.cs
  Bonsai.Core/Reactive/BufferTime.cs
  Bonsai.Core/Reactive/BufferTrigger.cs
  Bonsai.Core/Reactive/Concurrency/SchedulerMapping.cs
  Bonsai.Core/Reactive/Delay.cs
  Bonsai.Core/Reactive/DelaySubscription.cs
  Bonsai.Core/Reactive/Gate.cs
  Bonsai.Core/Reactive/GateInterval.cs
  Bonsai.Core/Reactive/Replay.cs
  Bonsai.Core/Reactive/SampleInterval.cs
  Bonsai.Core/Reactive/Subjects/ReplaySubject.cs
  Bonsai.Core/Reactive/Throttle.cs
  Bonsai.Core/Reactive/TimedGate.cs
  Bonsai.Core/Reactive/Timeout.cs
  Bonsai.Core/Reactive/Timer.cs
  Bonsai.Core/Reactive/WindowTime.cs
  Bonsai.Core/Reactive/WindowTrigger.cs
  Bonsai.Dsp/FirFilter.cs
  Bonsai.Dsp/IirFilter.cs
  Bonsai.Shaders/Delay.cs
  Bonsai.Shaders/DelaySubscription.cs
  Bonsai.Shaders/Timer.cs
  Bonsai.Vision/Drawing/AddTextBase.cs
  Bonsai.Vision/Drawing/CreateFont.cs
  Bonsai.Vision/Filter2D.cs
  Bonsai.Vision/WarpAffine.cs
Labels: feature

#1452 Add tie-break for method overloads in derived classes
  Bonsai.Core.Tests/OverloadedCombinatorBuilderTests.cs
  Bonsai.Core/Expressions/ExpressionBuilder.cs
Labels: fix

#1455 Improve information contrast for obsolete operators
  Bonsai.Editor/GraphModel/GraphNode.cs
  Bonsai.Editor/GraphView/GraphViewControl.cs
Labels: feature

#1456 Add support for streaming binary serial read buffers
  Bonsai.System/IO/Ports/ObservableSerialPort.cs
  Bonsai.System/IO/Ports/SerialRead.cs
Labels: feature

#1400 Ensure output of Normalize is bounded between zero and one
  Bonsai.Vision/Normalize.cs
Labels: fix

#1459 Require user defined conversion when multicasting to subject with non-matching type
  Bonsai.Core.Tests/CombinatorBuilderTests.cs
  Bonsai.Core.Tests/OverloadedCombinatorBuilderTests.cs
  Bonsai.Core.Tests/SubjectTests.cs
  Bonsai.Core.Tests/TypeConversionTests.cs
  Bonsai.Core/Expressions/MulticastSubject.cs
Labels: fix

#1460 Refactor matrix and spike visualizers to use buffered updates
  Bonsai.Dsp.Design/MatVisualizer.cs
  Bonsai.Dsp.Design/SpikeWaveformCollectionVisualizer.cs
Labels: feature

#1464 Allow starting editor session on a specified folder
  Bonsai.Design/FolderBrowserDialog.cs
  Bonsai.Design/FolderNameEditor.cs
  Bonsai.Editor/StartScreen.Designer.cs
  Bonsai.Editor/StartScreen.cs
  Bonsai.Editor/StartScreen.resx
  Bonsai/Program.cs
Labels: feature

#1466 Add citation file
  CITATION.cff
Labels: documentation

#1468 Ensure VideoWriter frame size is cached per subscription
  Bonsai.Vision/VideoWriter.cs
  Bonsai.Vision/VideoWriterDisposable.cs
Labels: fix

#1470 Ensure single row display for text visualizer
  Bonsai.Design/ObjectTextVisualizer.cs
Labels: fix

#1471 Improve cursor selection when clicking in editor empty space
  Bonsai.Editor/GraphView/GraphViewControl.cs
Labels: fix

#1472 Ensure restored bounds are at least in one screen
  Bonsai.Editor/EditorForm.cs
Labels: fix

#1479 Pack player project as a dotnet tool
  Bonsai.Player/Bonsai.Player.csproj
  Bonsai.Player/Program.cs
  icon.png
Labels: feature

#1481 Update bootstrapper to .NET 4.8
  .editorconfig
  Bonsai.Setup.Bootstrapper/Bonsai.Setup.Bootstrapper.wixproj
  Bonsai.Setup.Bootstrapper/Bundle.wxs
  Bonsai.Setup.Bootstrapper/NetFx472.wxs
  Bonsai.Setup.Bootstrapper/NetFx48.wxs
  Bonsai.Setup/Runtime.wxs
  Bonsai/Bonsai.csproj
  Bonsai/Launcher.cs
  Bonsai32/Bonsai32.csproj
Labels: feature

#1485 Disable caret selection from text visualizer
  Bonsai.Design/ObjectTextVisualizer.cs
  Bonsai.Design/RichTextLabel.cs
Labels: fix

#1487 Clear text visualizer on right double-click
  Bonsai.Design/ObjectTextVisualizer.cs
  Bonsai.Design/RichTextLabel.cs
Labels: feature

#1492 Add ReadAllText and WriteAllText operators
  Bonsai.System/IO/ReadAllText.cs
  Bonsai.System/IO/WriteAllText.cs
Labels: feature

#1497 Allow TypeMapping extension types
  Bonsai.Core/Expressions/InputMappingBuilder.cs
  Bonsai.Core/Expressions/MemberSelectorBuilder.cs
  Bonsai.Core/Expressions/TypeMapping.cs
  Bonsai.Core/Expressions/TypeMappingConverter.cs
  Bonsai.Core/Expressions/VisualizerMappingBuilder.cs
Labels: feature

#1498 Allow filtering which types to include in CollectionEditor
  Bonsai.System.Design/Resources/CollectionEditor.cs
Labels: feature

#1480 Enter the Bonsai Foundation
  Bonsai.Setup.Bootstrapper/Bundle.wxs
  Bonsai.Setup.Bootstrapper/License.rtf
  Bonsai.Setup/Product.wxs
  Bonsai.Setup/Runtime.wxs
  Bonsai.Templates/Bonsai.PackageTemplate/Properties/AssemblyInfo.cs
  Bonsai.Templates/Bonsai.PackageTemplate/launchSettings.json
  Bonsai.Templates/Bonsai.SinkTemplate/Properties/AssemblyInfo.cs
  Bonsai.Templates/Bonsai.SourceTemplate/Properties/AssemblyInfo.cs
  Bonsai.Templates/Bonsai.Templates/Properties/AssemblyInfo.cs
  Bonsai.Templates/Bonsai.Templates/eula.rtf
  Bonsai.Templates/Bonsai.Templates/source.extension.vsixmanifest
  Bonsai.Templates/Bonsai.TransformTemplate/Properties/AssemblyInfo.cs
  Bonsai.Templates/Bonsai.VisualizerTemplate/Properties/AssemblyInfo.cs
  Bonsai.Templates/Bonsai.WorkflowTemplate/Properties/AssemblyInfo.cs
  Directory.Build.props
  LICENSE
  README.md
Labels: documentation
