Repository bonsai-rx/bonsai, pull requests merged in 2024-08, with the labels that each got.

#1941 Rename CombineTimestamp to CreateTimestamped
  Bonsai.Core/Reactive/CombineTimestamp.cs
  Bonsai.Core/Reactive/CreateTimestamped.cs
Labels: feature, fix

#1942 Allow building workflows as typed sequences
  Bonsai.Core.Tests/ExpressionBuilderGraphTests.cs
  Bonsai.Core.Tests/TestWorkflow.cs
  Bonsai.Core/Expressions/ExpressionBuilder.cs
  Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs
  Bonsai.Core/Expressions/ExternalizedDateTimeOffset.cs
  Bonsai.Core/Expressions/ExternalizedProperty.cs
  Bonsai.Core/Expressions/ExternalizedTimeSpan.cs
Labels: feature

#1907 Target netcore on editor and bootstrapper projects
  .github/workflows/Bonsai.yml
  Bonsai.Configuration/Bonsai.Configuration.csproj
  Bonsai.Configuration/ConfigurationHelper.cs
  Bonsai.Configuration/PackageConfigurationUpdater.cs
  Bonsai.Configuration/ScriptExtensionsProvider.cs
  Bonsai.Core.Tests/Bonsai.Core.Tests.csproj
  Bonsai.Core/Bonsai.Core.csproj
  Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs
  Bonsai.Core/WorkflowBuildException.cs
  Bonsai.Core/WorkflowException.cs
  Bonsai.Core/WorkflowRuntimeException.cs
  Bonsai.Design/Bonsai.Design.csproj
  Bonsai.Design/MemberSelectorEditorController.cs
  Bonsai.Design/PropertyGrid.cs
  Bonsai.Design/TypeVisitor.cs
  Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj
  Bonsai.Editor/AboutBox.cs
  Bonsai.Editor/Bonsai.Editor.csproj
  Bonsai.Editor/EditorForm.cs
  Bonsai.Editor/GraphView/SvgRenderer.cs
  Bonsai.Editor/StartScreen.cs
  Bonsai.NuGet.Design/Bonsai.NuGet.Design.csproj
  Bonsai.NuGet.Design/LicenseAcceptanceDialog.cs
  Bonsai.NuGet.Design/PackageBuilderDialog.cs
  Bonsai.NuGet.Design/PackageManagerDialog.Designer.cs
  Bonsai.NuGet.Design/PackageSourceConfigurationDialog.Designer.cs
  Bonsai.NuGet.Design/PackageSourceConfigurationDialog.cs
  Bonsai.NuGet.Design/PackageSourceConfigurationDialog.resx
  Bonsai.NuGet.Design/Properties/Resources.Designer.cs
  Bonsai.NuGet.Design/Properties/Resources.resx
  Bonsai.NuGet/Bonsai.NuGet.csproj
  Bonsai.Player/Bonsai.Player.csproj
  Bonsai.System.Tests/Bonsai.System.Tests.csproj
  Bonsai.System/Bonsai.System.csproj
  Bonsai/Bonsai.csproj
  Bonsai/EditorBootstrapper.cs
  Bonsai/Launcher.cs
  Bonsai/LoaderResource.cs
  Bonsai/Program.cs
  Bonsai/Properties/Resources.Designer.cs
  tooling/Common.csproj.props
  tooling/CurrentVersion.props
Labels: feature

#1952 Configure tests to run on .NET 8
  Bonsai.Core.Tests/Bonsai.Core.Tests.csproj
  Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj
  Bonsai.System.Tests/Bonsai.System.Tests.csproj
Labels: feature

#1957 Make period a nullable property of reactive timer and clarify documentation
  Bonsai.Core/Reactive/Timer.cs
  Bonsai.Shaders/Timer.cs
Labels: fix

#1958 Fix test target framework issues
  .github/workflows/Bonsai.yml
  Bonsai.Core.Tests/Bonsai.Core.Tests.csproj
  Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj
  Bonsai.System.Tests/Bonsai.System.Tests.csproj
  tooling/Common.Tests.csproj.props
  tooling/Common.csproj.props
Labels: fix

#1946 Exclude build dependencies when counting inputs to new nested node
  Bonsai.Core.Tests/TestWorkflow.cs
  Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj
  Bonsai.Editor.Tests/WorkflowEditorTests.cs
  Bonsai.Editor/GraphModel/WorkflowEditor.cs
Labels: fix

#1964 Add support for sorting test workflows
  Bonsai.Core.Tests/TestWorkflow.cs
  Bonsai.Editor.Tests/WorkflowEditorTests.cs
Labels: feature
