Repository bonsai-rx/bonsai, pull requests merged in 2024-05, with the labels that each got.

#1768 Clarify use of cross-correlation for FIR filters
  Bonsai.Dsp/FirFilter.cs
Labels: documentation, fix

#1785 Fixed uncaught exception when XRefMap is invalid
  Bonsai.Editor/DocumentationException.cs
  Bonsai.Editor/DocumentationHelper.cs
  Bonsai.Editor/EditorForm.cs
Labels: fix

#1788 Enable support for compressed XRefMap from documentation server
  Bonsai.Editor/DocumentationHelper.cs
Labels: feature

#1754 Move arduino package into separate repository
  .git-blame-ignore-revs
  Bonsai.Arduino/AnalogInput.cs
  Bonsai.Arduino/AnalogInputReceivedEventArgs.cs
  Bonsai.Arduino/AnalogOutput.cs
  Bonsai.Arduino/Arduino.cs
  Bonsai.Arduino/ArduinoConfiguration.cs
  Bonsai.Arduino/ArduinoConfigurationCollection.cs
  Bonsai.Arduino/ArduinoDisposable.cs
  Bonsai.Arduino/ArduinoManager.cs
  Bonsai.Arduino/Bonsai.Arduino.csproj
  Bonsai.Arduino/CreateArduino.cs
  Bonsai.Arduino/DigitalInput.cs
  Bonsai.Arduino/DigitalInputReceivedEventArgs.cs
  Bonsai.Arduino/DigitalOutput.cs
  Bonsai.Arduino/InputPullUp.cs
  Bonsai.Arduino/ObservableArduino.cs
  Bonsai.Arduino/PortNameConverter.cs
  Bonsai.Arduino/Properties/AssemblyInfo.cs
  Bonsai.Arduino/Properties/launchSettings.json
  Bonsai.Arduino/ReceiveSysex.cs
  Bonsai.Arduino/SendSysex.cs
  Bonsai.Arduino/ServoOutput.cs
  Bonsai.Arduino/SysexReceivedEventArgs.cs
  Bonsai.StarterPack/Bonsai.StarterPack.csproj
  Bonsai.sln
Labels: feature, dependencies

#1805 Log full exception trace for console bootstrap
  Bonsai.Configuration/ConsoleBootstrapper.cs
Labels: fix

#1787 Prevent infinite recursion when visualizer mappings of the same node are combined together
  Bonsai.Editor/Layout/LayoutHelper.cs
Labels: fix

#1810 Update project and item template dependencies
  Bonsai.Templates/Bonsai.PackageTemplate/ProjectTemplate.csproj
  Bonsai.Templates/Bonsai.SinkTemplate/Bonsai.SinkTemplate.vstemplate
  Bonsai.Templates/Bonsai.SourceTemplate/Bonsai.SourceTemplate.vstemplate
  Bonsai.Templates/Bonsai.Templates.csproj
  Bonsai.Templates/Bonsai.Templates/source.extension.vsixmanifest
  Bonsai.Templates/Bonsai.TransformTemplate/Bonsai.TransformTemplate.vstemplate
  Bonsai.Templates/Bonsai.VisualizerTemplate/Bonsai.VisualizerTemplate.vstemplate
Labels: feature
