Repository bonsai-rx/bonsai, pull requests merged in 2024-07, with the labels that each got.

#1878 Move ironpython package into separate repository
  Bonsai.Scripting.IronPython.Design/Bonsai.Scripting.IronPython.Design.csproj
  Bonsai.Scripting.IronPython.Design/Properties/launchSettings.json
  Bonsai.Scripting.IronPython.Design/PythonScriptEditor.cs
  Bonsai.Scripting.IronPython.Design/PythonScriptEditorDialog.Designer.cs
  Bonsai.Scripting.IronPython.Design/PythonScriptEditorDialog.cs
  Bonsai.Scripting.IronPython.Design/PythonScriptEditorDialog.resx
  Bonsai.Scripting.IronPython/Bonsai.Scripting.IronPython.csproj
  Bonsai.Scripting.IronPython/IScriptingElement.cs
  Bonsai.Scripting.IronPython/Properties/AssemblyInfo.cs
  Bonsai.Scripting.IronPython/Properties/launchSettings.json
  Bonsai.Scripting.IronPython/PythonEngine.cs
  Bonsai.Scripting.IronPython/PythonHelper.cs
  Bonsai.Scripting.IronPython/PythonProcessor.cs
  Bonsai.Scripting.IronPython/PythonSelectMany.cs
  Bonsai.Scripting.IronPython/PythonSource.cs
  Bonsai.Scripting.IronPython/PythonTransform.cs
  Bonsai.Scripting.IronPython/ScriptingElementTypeDescriptor.cs
  Bonsai.Scripting/Bonsai.Scripting.csproj
  Bonsai.Scripting/ExpressionCondition.cs
  Bonsai.Scripting/ExpressionSink.cs
  Bonsai.Scripting/ExpressionTransform.cs
  Bonsai.Scripting/IScriptingElement.cs
  Bonsai.Scripting/Properties/AssemblyInfo.cs
  Bonsai.Scripting/Properties/launchSettings.json
  Bonsai.Scripting/PythonCondition.cs
  Bonsai.Scripting/PythonEngine.cs
  Bonsai.Scripting/PythonHelper.cs
  Bonsai.Scripting/PythonProcessor.cs
  Bonsai.Scripting/PythonSelectMany.cs
  Bonsai.Scripting/PythonSink.cs
  Bonsai.Scripting/PythonSource.cs
  Bonsai.Scripting/PythonTextWriter.cs
  Bonsai.Scripting/PythonTransform.cs
  Bonsai.Scripting/ScriptingElementTypeDescriptor.cs
  Bonsai.sln
Labels: feature

#1888 Log all unhandled bootstrapper exceptions
  Bonsai.Configuration/ConsoleBootstrapper.cs
  Bonsai/Program.cs
Labels: fix

#1894 Hide embedded DLLs from the solution explorer
  Bonsai/Bonsai.csproj
Labels: fix

#1882 Fix `ObjectTextVisualizer` allowing a buffer size of 0
  Bonsai.Design/ObjectTextVisualizer.cs
Labels: fix

#1889 Ensure visualizer operator override
  Bonsai.Core.Tests/InspectBuilderTests.cs
  Bonsai.Core.Tests/TestWorkflow.cs
  Bonsai.Core/Reactive/Sink.cs
  Bonsai.Core/Reactive/Visualizer.cs
  tooling/Common.csproj.props
Labels: fix

#1893 Use forward slashes for package configuration
  Bonsai.Configuration/AssemblyLocationCollection.cs
  Bonsai.Configuration/ConfigurationHelper.cs
  Bonsai.Configuration/PackageConfigurationUpdater.cs
Labels: fix

#1890 Preload all extension types from include workflows
  Bonsai.Core/Expressions/IncludeWorkflowBuilder.cs
  Bonsai.Core/WorkflowBuilder.cs
Labels: fix

#1902 Fix redundant assembly resolution resulting in duplicate assembly loading
  Bonsai/Bonsai.csproj
  Bonsai/SystemResourcesExtensionsSupport.cs
Labels: fix

#1904 Ensure all resolved assemblies are unique
  Bonsai.Configuration/ConfigurationHelper.cs
Labels: fix

#1908 Fix some lists in the NuGet package comparison log not being sorted
  .github/workflows/compare-nuget-packages.py
Labels: fix

#1909 Add Discord and GitHub Discussions badges to the readme
  README.md
Labels: documentation

#1918 Fix NuGet testing feed appearing in official releases
  .github/workflows/create-portable-zip.py
Labels: fix

#1910 Fix exception constructor argument order
  .editorconfig
  Bonsai.Core/Dag/DirectedGraph.cs
  Bonsai.Core/Reactive/Slice.cs
Labels: fix

#1913 Drop version build metadata for official releases
  Bonsai.Core/WorkflowBuilder.cs
  Bonsai.Editor/AboutBox.cs
Labels: fix

#1916 Ensure multicast subject preserves source type
  Bonsai.Core.Tests/SubjectTests.cs
  Bonsai.Core.Tests/TestWorkflow.cs
  Bonsai.Core/Expressions/MulticastSubject.cs
Labels: fix

#1923 Update launch settings to target artifacts folder
  Bonsai.Audio/Properties/launchSettings.json
  Bonsai.Design.Visualizers/Properties/launchSettings.json
  Bonsai.Dsp.Design/Properties/launchSettings.json
  Bonsai.Dsp/Properties/launchSettings.json
  Bonsai.Osc/Properties/launchSettings.json
  Bonsai.Scripting.Expressions.Design/Properties/launchSettings.json
  Bonsai.Scripting.Expressions/Properties/launchSettings.json
  Bonsai.Shaders.Design/Properties/launchSettings.json
  Bonsai.Shaders.Rendering/Properties/launchSettings.json
  Bonsai.Shaders/Properties/launchSettings.json
  Bonsai.System.Design/Properties/launchSettings.json
  Bonsai.System/Properties/launchSettings.json
  Bonsai.Vision.Design/Properties/launchSettings.json
  Bonsai.Vision/Properties/launchSettings.json
  Bonsai.Windows.Input/Properties/launchSettings.json
  tooling/Common.props
Labels: fix

#1924 Update ScintillaNET to support modern .NET
  Bonsai.Audio/Bonsai.Audio.csproj
  Bonsai.Core.Tests/Bonsai.Core.Tests.csproj
  Bonsai.Core/Bonsai.Core.csproj
  Bonsai.Design.Visualizers/Bonsai.Design.Visualizers.csproj
  Bonsai.Design/Bonsai.Design.csproj
  Bonsai.Dsp.Design/Bonsai.Dsp.Design.csproj
  Bonsai.Dsp/Bonsai.Dsp.csproj
  Bonsai.Osc/Bonsai.Osc.csproj
  Bonsai.Scripting.Expressions.Design/Bonsai.Scripting.Expressions.Design.csproj
  Bonsai.Scripting.Expressions/Bonsai.Scripting.Expressions.csproj
  Bonsai.Shaders.Design/Bonsai.Shaders.Design.csproj
  Bonsai.Shaders.Rendering/Bonsai.Shaders.Rendering.csproj
  Bonsai.Shaders/Bonsai.Shaders.csproj
  Bonsai.StarterPack/Bonsai.StarterPack.csproj
  Bonsai.System.Design/Bonsai.System.Design.csproj
  Bonsai.System.Tests/Bonsai.System.Tests.csproj
  Bonsai.System/Bonsai.System.csproj
  Bonsai.Vision.Design/Bonsai.Vision.Design.csproj
  Bonsai.Vision/Bonsai.Vision.csproj
  Bonsai.Windows.Input/Bonsai.Windows.Input.csproj
Labels: feature, fix

#1931 Allow propagation of Defer nested sequence visualizer
  Bonsai.Core.Tests/InspectBuilderTests.cs
  Bonsai.Core.Tests/TestWorkflow.cs
  Bonsai.Core/Expressions/InspectBuilder.cs
  Bonsai.Core/Reactive/Defer.cs
Labels: feature

#1937 Replace uses of WebRequest with HttpClient
  Bonsai.Editor/Bonsai.Editor.csproj
  Bonsai.Editor/DocumentationHelper.cs
  Bonsai.NuGet.Design/IconReader.cs
  Bonsai.NuGet.Design/PackageViewController.cs
Labels: feature, fix
