Repository bonsai-rx/bonsai, pull requests merged in 2025-06, with the labels that each got.

#2316 Add command for creating a new environment
  Bonsai.Configuration/Bootstrapper.cs
  Bonsai.Configuration/BootstrapperInfo.cs
  Bonsai.Configuration/CommandLineParser.cs
  Bonsai.Configuration/ConsoleEnvironmentBootstrapper.cs
  Bonsai.Configuration/EnvironmentBootstrapper.cs
  Bonsai.Configuration/EnvironmentSelector.cs
  Bonsai.Configuration/IEnvironmentBootstrapper.cs
  Bonsai.Configuration/ScriptExtensions.cs
  Bonsai.Editor/EditorForm.cs
  Bonsai.Editor/EditorSettings.cs
  Bonsai.Setup.Bootstrapper/Bundle.wxs
  Bonsai.Setup.Bootstrapper/Theme/RtfLargeTheme.xml
  Bonsai.Setup/Bonsai.Setup.wixproj
  Bonsai.Setup/NuGet.config
  Bonsai.Setup/Product.wxs
  Bonsai.Setup/Runtime.wxs
  Bonsai/DependencyInspector.cs
  Bonsai/EditorEnvironmentBootstrapper.cs
  Bonsai/Program.cs
Labels: feature

#2353 Update spelling of open source to match convention
  Bonsai.Audio/README.md
  Bonsai.Core/README.md
  Bonsai.Design.Visualizers/README.md
  Bonsai.Design/README.md
  Bonsai.Dsp.Design/README.md
  Bonsai.Dsp/README.md
  Bonsai.Editor/README.md
  Bonsai.Osc/README.md
  Bonsai.Player/README.md
  Bonsai.Scripting.Expressions.Design/README.md
  Bonsai.Scripting.Expressions/README.md
  Bonsai.Shaders.Design/README.md
  Bonsai.Shaders.Rendering/README.md
  Bonsai.Shaders/README.md
  Bonsai.StarterPack/README.md
  Bonsai.System.Design/README.md
  Bonsai.System/README.md
  Bonsai.Templates/README.md
  Bonsai.Vision.Design/README.md
  Bonsai.Vision/README.md
  Bonsai.Windows.Input/README.md
  Bonsai/README.md
Labels: documentation

#2358 Add missing editor default properties
  Bonsai.Shaders/WarpPerspective.cs
  Bonsai.Vision/CropPolygon.cs
  Bonsai.Vision/Drawing/CropCanvas.cs
  Bonsai.Vision/GoodFeaturesToTrack.cs
Labels: feature

#2363 Rename save workflow extension menu item
  Bonsai.Editor/EditorForm.Designer.cs
  Bonsai.Editor/EditorForm.cs
  Bonsai.Editor/GraphView/WorkflowGraphView.Designer.cs
  Bonsai.Editor/GraphView/WorkflowGraphView.cs
Labels: feature, fix

#2364 Fix tooltip for `New` workflow button on toolbar
  Bonsai.Editor/EditorForm.Designer.cs
Labels: fix

#2366 Fix search filter to allow legacy package update
  Bonsai.NuGet/SourceRepositoryExtensions.cs
  Bonsai.NuGet/UpdateQuery.cs
  Bonsai/Launcher.cs
Labels: fix
